Traceback (most recent call last):
  File "effective_numbers.py", line 4, in <module>
    from .initialize import *
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "effective_numbers.py", line 4, in <module>
    from .initialize import *
ImportError: attempted relative import with no known parent package
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py:623> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
    self.http_server.listen(**http_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
    self.start_http_server(routes, self._dashboard_address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
    self.http_server.listen(**tlz.merge(http_address, {"port": 0}))
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 232, in start_http_server
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_numbers.py", line 165, in <module>
  File "run_numbers.py", line 149, in compute_with_dask
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 728, in __init__
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 932, in start
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/utils.py", line 347, in sync
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/utils.py", line 331, in f
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 1001, in _start
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/deploy/spec.py", line 366, in _
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/deploy/spec.py", line 335, in _correct_state_internal
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1037, in start
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/node.py", line 235, in start_http_server
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 140, in bind_sockets
  File "/Users/caganze/anaconda3/lib/python3.7/socket.py", line 151, in __init__
OSError: [Errno 24] Too many open files
distributed.diskutils - ERROR - Failed to remove '/Users/caganze/research/wisps/wisps/simulations/dask-worker-space/worker-z9kw3haj' (failed in <built-in function scandir>): [Errno 24] Too many open files: '/Users/caganze/research/wisps/wisps/simulations/dask-worker-space/worker-z9kw3haj'
distributed.diskutils - ERROR - Failed to remove '/Users/caganze/research/wisps/wisps/simulations/dask-worker-space/worker-z9kw3haj' (failed in <built-in function rmdir>): [Errno 66] Directory not empty: '/Users/caganze/research/wisps/wisps/simulations/dask-worker-space/worker-z9kw3haj'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/caganze/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/utils.py", line 198, in ignoring
    yield
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/deploy/spec.py", line 611, in close_clusters
    cluster.close(timeout=10)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 84, in close
    return self.sync(self._close, callback_timeout=timeout)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 163, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/utils.py", line 347, in sync
    raise exc.with_traceback(tb)
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/utils.py", line 331, in f
    result[0] = yield future
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/deploy/spec.py", line 393, in _close
    assert w.status == "closed", w.status
AssertionError: None
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6572e650>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6d90>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6ab53290>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6ab53190>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6ed0>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6ab53090>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6f90>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6dd0>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6d50>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6a50>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6990>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6f10>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6a10>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6b50>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6ad0>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6a90>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6ab532d0>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6fd0>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6ab53050>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6c10>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6b10>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6cd0>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6c50>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa69d0>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6b90>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6ab53250>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6ab53210>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6f50>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6e10>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6aaa6d10>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6ab53310>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6ab53110>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6ab530d0>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<InProcListener._listen() running at /Users/caganze/anaconda3/lib/python3.7/site-packages/distributed/comm/inproc.py:250> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1a6ab53150>()]>>
  0%|          | 0/25 [00:00<?, ?it/s]Adding 145 sources from /Users/caganze/research/splat//resources/Spectra/Public/LRIS-RED/ to spectral database
Adding 2404 sources from /Users/caganze/research/splat//resources/Spectra/Public/SPEX-PRISM/ to spectral database
Adding 89 sources from /Users/caganze/research/splat//resources/Spectra/Public/MAGE/ to spectral database
['aegis-01', 'aegis-02', 'aegis-03', 'aegis-04', 'aegis-05', 'aegis-06', 'aegis-07', 'aegis-08', 'aegis-09', 'aegis-10', 'aegis-12', 'aegis-13', 'aegis-14', 'aegis-15', 'aegis-18', 'aegis-19', 'aegis-21', 'aegis-23', 'aegis-24', 'aegis-25', 'aegis-26', 'aegis-27', 'aegis-28', 'aegis-11', 'cosmos-01', 'cosmos-03', 'cosmos-04', 'cosmos-05', 'cosmos-06', 'cosmos-07', 'cosmos-08', 'cosmos-09', 'cosmos-10', 'cosmos-11', 'cosmos-12', 'cosmos-13', 'cosmos-14', 'cosmos-15', 'cosmos-16', 'cosmos-17', 'cosmos-18', 'cosmos-19', 'cosmos-20', 'cosmos-21', 'cosmos-22', 'cosmos-23', 'cosmos-24', 'cosmos-25', 'cosmos-26', 'cosmos-27', 'cosmos-28', 'cosmos-02', 'uds-01', 'uds-02', 'uds-03', 'uds-04', 'uds-05', 'uds-06', 'uds-07', 'uds-08', 'uds-09', 'uds-10', 'uds-11', 'uds-12', 'uds-13', 'uds-14', 'uds-15', 'uds-17', 'uds-18', 'uds-20', 'uds-21', 'uds-22', 'uds-23', 'uds-24', 'uds-25', 'uds-26', 'uds-27', 'uds-28', 'uds-16', 'uds-19', 'goodsn-11', 'goodsn-111', 'goodsn-114', 'goodsn-12', 'goodsn-13', 'goodsn-14', 'goodsn-15', 'goodsn-16', 'goodsn-18', 'goodsn-23', 'goodsn-24', 'goodsn-25', 'goodsn-26', 'goodsn-27', 'goodsn-28', 'goodsn-31', 'goodsn-32', 'goodsn-34', 'goodsn-35', 'goodsn-36', 'goodsn-41', 'goodsn-42', 'goodsn-43', 'goodsn-44', 'goodsn-45', 'goodsn-46', 'goodss-01', 'goodss-02', 'goodss-03', 'goodss-04', 'goodss-05', 'goodss-06', 'goodss-08', 'goodss-09', 'goodss-10', 'goodss-11', 'goodss-12', 'goodss-13', 'goodss-14', 'goodss-15', 'goodss-16', 'goodss-17', 'goodss-18', 'goodss-19', 'goodss-20', 'goodss-21', 'goodss-22', 'goodss-24', 'goodss-25', 'goodss-26', 'goodss-27', 'goodss-28', 'goodss-29', 'goodss-30', 'goodss-31', 'goodss-32', 'goodss-33', 'goodss-34', 'goodss-35', 'goodss-36', 'goodss-37', 'goodss-38', 'goodsn-17', 'goodsn-21', 'goodsn-22', 'goodsn-33', 'goodss-07', 'goodsn-123', 'par334', 'par1', 'par10', 'par101', 'par103', 'par104', 'par105', 'par106', 'par107', 'par108', 'par11', 'par110', 'par111', 'par114', 'par115', 'par116', 'par119', 'par12', 'par120', 'par121', 'par122', 'par123', 'par124', 'par125', 'par126', 'par127', 'par128', 'par129', 'par13', 'par130', 'par132', 'par133', 'par134', 'par135', 'par136', 'par137', 'par138', 'par139', 'par14', 'par140', 'par141', 'par143', 'par144', 'par145', 'par146', 'par147', 'par148', 'par149', 'par15', 'par150', 'par151', 'par152', 'par153', 'par154', 'par155', 'par156', 'par157', 'par158', 'par159', 'par16', 'par160', 'par161', 'par162', 'par163', 'par165', 'par166', 'par167', 'par168', 'par169', 'par17', 'par170', 'par171', 'par172', 'par173', 'par174', 'par175', 'par176', 'par177', 'par179', 'par18', 'par181', 'par182', 'par183', 'par186', 'par188', 'par189', 'par19', 'par190', 'par191', 'par192', 'par193', 'par194', 'par195', 'par196', 'par197', 'par198', 'par199', 'par2', 'par20', 'par200', 'par201', 'par202', 'par203', 'par204', 'par205', 'par206', 'par209', 'par21', 'par210', 'par211', 'par212', 'par214', 'par215', 'par216', 'par217', 'par218', 'par219', 'par22', 'par220', 'par221', 'par222', 'par224', 'par226', 'par227', 'par228', 'par229', 'par23', 'par231', 'par232', 'par233', 'par234', 'par235', 'par236', 'par237', 'par238', 'par239', 'par24', 'par240', 'par241', 'par242', 'par243', 'par244', 'par245', 'par246', 'par247', 'par248', 'par249', 'par25', 'par250', 'par251', 'par252', 'par256', 'par257', 'par258', 'par259', 'par26', 'par260', 'par261', 'par262', 'par263', 'par264', 'par267', 'par268', 'par269', 'par27', 'par270', 'par271', 'par272', 'par273', 'par275', 'par277', 'par279', 'par28', 'par281', 'par288', 'par289', 'par29', 'par290', 'par292', 'par293', 'par294', 'par295', 'par297', 'par299', 'par30', 'par300', 'par301', 'par302', 'par303', 'par304', 'par307', 'par308', 'par309', 'par31', 'par311', 'par312', 'par313', 'par314', 'par315', 'par317', 'par319', 'par32', 'par320', 'par321', 'par322', 'par324', 'par325', 'par326', 'par328', 'par330', 'par332', 'par333', 'par335', 'par336', 'par337', 'par338', 'par34', 'par340', 'par341', 'par342', 'par343', 'par345', 'par346', 'par347', 'par348', 'par349', 'par35', 'par350', 'par352', 'par353', 'par354', 'par355', 'par356', 'par357', 'par358', 'par359', 'par36', 'par360', 'par361', 'par362', 'par364', 'par365', 'par367', 'par368', 'par369', 'par37', 'par370', 'par371', 'par372', 'par374', 'par375', 'par377', 'par378', 'par38', 'par380', 'par381', 'par382', 'par385', 'par386', 'par387', 'par388', 'par389', 'par39', 'par391', 'par394', 'par395', 'par396', 'par397', 'par398', 'par40', 'par400', 'par403', 'par404', 'par405', 'par406', 'par408', 'par409', 'par41', 'par411', 'par412', 'par413', 'par416', 'par417', 'par420', 'par422', 'par425', 'par427', 'par428', 'par43', 'par430', 'par431', 'par432', 'par433', 'par434', 'par435', 'par436', 'par437', 'par438', 'par439', 'par44', 'par440', 'par441', 'par442', 'par443', 'par444', 'par445', 'par446', 'par449', 'par45', 'par450', 'par451', 'par452', 'par453', 'par454', 'par456', 'par457', 'par458', 'par46', 'par461', 'par462', 'par463', 'par464', 'par465', 'par466', 'par467', 'par468', 'par469', 'par47', 'par471', 'par472', 'par473', 'par474', 'par476', 'par477', 'par478', 'par480', 'par481', 'par482', 'par483', 'par49', 'par5', 'par50', 'par51', 'par52', 'par53', 'par54', 'par55', 'par56', 'par57', 'par58', 'par59', 'par6', 'par64', 'par65', 'par66', 'par68', 'par69', 'par71', 'par72', 'par73', 'par74', 'par75', 'par76', 'par77', 'par79', 'par80', 'par81', 'par82', 'par83', 'par84', 'par85', 'par86', 'par87', 'par88', 'par89', 'par90', 'par91', 'par92', 'par93', 'par94', 'par95', 'par96', 'par97', 'par98', 'par99']
  4%|▍         | 1/25 [00:22<08:57, 22.38s/it]  8%|▊         | 2/25 [00:45<08:37, 22.49s/it] 12%|█▏        | 3/25 [01:08<08:19, 22.71s/it] 16%|█▌        | 4/25 [01:31<07:58, 22.80s/it] 20%|██        | 5/25 [01:54<07:37, 22.86s/it] 24%|██▍       | 6/25 [02:20<07:30, 23.73s/it] 28%|██▊       | 7/25 [02:44<07:09, 23.86s/it] 32%|███▏      | 8/25 [03:08<06:46, 23.91s/it] 36%|███▌      | 9/25 [03:32<06:25, 24.07s/it] 40%|████      | 10/25 [03:57<06:02, 24.16s/it] 44%|████▍     | 11/25 [04:22<05:42, 24.46s/it] 48%|████▊     | 12/25 [04:47<05:20, 24.68s/it] 52%|█████▏    | 13/25 [05:13<04:59, 24.94s/it] 56%|█████▌    | 14/25 [05:38<04:35, 25.05s/it] 60%|██████    | 15/25 [06:04<04:13, 25.36s/it] 64%|██████▍   | 16/25 [06:30<03:50, 25.59s/it] 68%|██████▊   | 17/25 [06:56<03:26, 25.80s/it] 72%|███████▏  | 18/25 [07:26<03:09, 27.01s/it] 76%|███████▌  | 19/25 [07:53<02:41, 26.99s/it] 80%|████████  | 20/25 [08:20<02:15, 27.02s/it] 84%|████████▍ | 21/25 [08:47<01:47, 26.91s/it] 88%|████████▊ | 22/25 [09:15<01:21, 27.23s/it] 92%|█████████▏| 23/25 [09:42<00:54, 27.32s/it] 96%|█████████▌| 24/25 [10:11<00:27, 27.62s/it]100%|██████████| 25/25 [10:39<00:00, 27.87s/it]100%|██████████| 25/25 [10:39<00:00, 25.59s/it]
  0%|          | 0/25 [00:00<?, ?it/s]  4%|▍         | 1/25 [00:28<11:32, 28.85s/it]  8%|▊         | 2/25 [00:58<11:07, 29.04s/it] 12%|█▏        | 3/25 [01:27<10:37, 28.99s/it] 16%|█▌        | 4/25 [02:00<10:37, 30.34s/it] 20%|██        | 5/25 [02:30<10:01, 30.09s/it] 24%|██▍       | 6/25 [03:00<09:35, 30.28s/it] 28%|██▊       | 7/25 [03:31<09:07, 30.41s/it] 32%|███▏      | 8/25 [04:03<08:43, 30.82s/it] 36%|███▌      | 9/25 [04:34<08:13, 30.86s/it] 40%|████      | 10/25 [05:06<07:47, 31.20s/it] 44%|████▍     | 11/25 [05:38<07:19, 31.38s/it] 48%|████▊     | 12/25 [06:09<06:49, 31.49s/it] 52%|█████▏    | 13/25 [06:42<06:23, 31.96s/it] 56%|█████▌    | 14/25 [07:15<05:53, 32.15s/it] 60%|██████    | 15/25 [07:48<05:23, 32.38s/it] 64%|██████▍   | 16/25 [08:20<04:50, 32.31s/it] 68%|██████▊   | 17/25 [08:54<04:21, 32.73s/it] 72%|███████▏  | 18/25 [09:27<03:50, 32.87s/it] 76%|███████▌  | 19/25 [09:59<03:16, 32.70s/it] 80%|████████  | 20/25 [10:35<02:48, 33.61s/it] 84%|████████▍ | 21/25 [11:08<02:13, 33.41s/it] 88%|████████▊ | 22/25 [11:41<01:40, 33.40s/it] 92%|█████████▏| 23/25 [12:28<01:14, 37.37s/it] 96%|█████████▌| 24/25 [13:02<00:36, 36.39s/it]100%|██████████| 25/25 [13:35<00:00, 35.49s/it]100%|██████████| 25/25 [13:36<00:00, 32.64s/it]
  0%|          | 0/25 [00:00<?, ?it/s]  4%|▍         | 1/25 [00:37<15:10, 37.94s/it]  8%|▊         | 2/25 [01:12<14:09, 36.92s/it] 12%|█▏        | 3/25 [01:47<13:17, 36.27s/it] 16%|█▌        | 4/25 [02:23<12:43, 36.37s/it] 20%|██        | 5/25 [02:58<11:57, 35.90s/it] 24%|██▍       | 6/25 [03:36<11:35, 36.61s/it] 28%|██▊       | 7/25 [04:15<11:08, 37.15s/it] 32%|███▏      | 8/25 [04:51<10:29, 37.00s/it] 36%|███▌      | 9/25 [05:28<09:51, 36.99s/it] 40%|████      | 10/25 [06:08<09:25, 37.72s/it] 44%|████▍     | 11/25 [06:49<09:02, 38.72s/it] 48%|████▊     | 12/25 [07:27<08:21, 38.59s/it] 52%|█████▏    | 13/25 [08:05<07:40, 38.35s/it] 56%|█████▌    | 14/25 [08:51<07:27, 40.70s/it] 60%|██████    | 15/25 [09:30<06:40, 40.03s/it] 64%|██████▍   | 16/25 [10:09<05:57, 39.77s/it] 68%|██████▊   | 17/25 [10:48<05:16, 39.62s/it] 72%|███████▏  | 18/25 [11:29<04:40, 40.01s/it] 76%|███████▌  | 19/25 [12:09<03:59, 39.95s/it] 80%|████████  | 20/25 [12:49<03:19, 39.90s/it] 84%|████████▍ | 21/25 [13:30<02:41, 40.41s/it] 88%|████████▊ | 22/25 [14:22<02:11, 43.73s/it] 92%|█████████▏| 23/25 [15:04<01:26, 43.25s/it] 96%|█████████▌| 24/25 [15:45<00:42, 42.57s/it]100%|██████████| 25/25 [16:27<00:00, 42.37s/it]100%|██████████| 25/25 [16:27<00:00, 39.49s/it]
  0%|          | 0/25 [00:00<?, ?it/s]  4%|▍         | 1/25 [01:04<25:46, 64.43s/it]  8%|▊         | 2/25 [01:52<22:45, 59.37s/it] 12%|█▏        | 3/25 [02:46<21:15, 57.98s/it] 16%|█▌        | 4/25 [03:33<19:03, 54.47s/it] 20%|██        | 5/25 [04:28<18:15, 54.79s/it] 24%|██▍       | 6/25 [05:28<17:47, 56.20s/it] 28%|██▊       | 7/25 [06:17<16:16, 54.23s/it] 32%|███▏      | 8/25 [07:05<14:49, 52.34s/it] 36%|███▌      | 9/25 [07:55<13:45, 51.62s/it] 40%|████      | 10/25 [09:00<13:52, 55.52s/it] 44%|████▍     | 11/25 [09:53<12:48, 54.92s/it] 48%|████▊     | 12/25 [10:51<12:05, 55.78s/it] 52%|█████▏    | 13/25 [11:38<10:38, 53.23s/it] 56%|█████▌    | 14/25 [12:27<09:31, 51.91s/it] 60%|██████    | 15/25 [13:38<09:37, 57.75s/it] 64%|██████▍   | 16/25 [14:26<08:11, 54.63s/it] 68%|██████▊   | 17/25 [15:14<07:00, 52.61s/it] 72%|███████▏  | 18/25 [16:06<06:07, 52.46s/it] 76%|███████▌  | 19/25 [16:54<05:07, 51.18s/it] 80%|████████  | 20/25 [18:19<05:06, 61.31s/it] 84%|████████▍ | 21/25 [20:22<05:19, 79.98s/it] 88%|████████▊ | 22/25 [21:24<03:42, 74.33s/it] 92%|█████████▏| 23/25 [22:16<02:15, 67.84s/it] 96%|█████████▌| 24/25 [23:34<01:10, 70.84s/it]100%|██████████| 25/25 [24:42<00:00, 69.97s/it]100%|██████████| 25/25 [24:42<00:00, 59.30s/it]
  0%|          | 0/25 [00:00<?, ?it/s]  4%|▍         | 1/25 [01:05<26:08, 65.34s/it]  8%|▊         | 2/25 [02:00<23:55, 62.40s/it] 12%|█▏        | 3/25 [02:58<22:20, 60.92s/it] 16%|█▌        | 4/25 [03:56<21:01, 60.08s/it] 20%|██        | 5/25 [04:51<19:29, 58.46s/it] 24%|██▍       | 6/25 [06:03<19:48, 62.54s/it] 28%|██▊       | 7/25 [07:02<18:29, 61.66s/it] 32%|███▏      | 8/25 [08:13<18:15, 64.45s/it] 36%|███▌      | 9/25 [09:22<17:29, 65.59s/it] 40%|████      | 10/25 [10:31<16:39, 66.64s/it] 44%|████▍     | 11/25 [11:33<15:16, 65.43s/it] 48%|████▊     | 12/25 [12:50<14:55, 68.88s/it] 52%|█████▏    | 13/25 [14:18<14:55, 74.60s/it] 56%|█████▌    | 14/25 [15:41<14:07, 77.03s/it] 60%|██████    | 15/25 [17:00<12:57, 77.71s/it] 64%|██████▍   | 16/25 [18:38<12:34, 83.86s/it] 68%|██████▊   | 17/25 [20:13<11:36, 87.11s/it] 72%|███████▏  | 18/25 [21:58<10:46, 92.42s/it] 76%|███████▌  | 19/25 [23:46<09:42, 97.11s/it] 80%|████████  | 20/25 [25:36<08:25, 101.14s/it] 84%|████████▍ | 21/25 [27:20<06:48, 102.01s/it] 88%|████████▊ | 22/25 [29:07<05:10, 103.51s/it] 92%|█████████▏| 23/25 [30:50<03:26, 103.15s/it] 96%|█████████▌| 24/25 [32:44<01:46, 106.42s/it]100%|██████████| 25/25 [34:24<00:00, 104.65s/it]100%|██████████| 25/25 [34:24<00:00, 82.59s/it] 
  0%|          | 0/25 [00:00<?, ?it/s]  4%|▍         | 1/25 [02:28<59:33, 148.92s/it]  8%|▊         | 2/25 [04:57<56:59, 148.69s/it] 12%|█▏        | 3/25 [07:41<56:14, 153.41s/it] 16%|█▌        | 4/25 [10:35<55:52, 159.65s/it] 20%|██        | 5/25 [13:29<54:38, 163.90s/it] 24%|██▍       | 6/25 [16:48<55:12, 174.37s/it] 28%|██▊       | 7/25 [19:28<51:03, 170.18s/it] 32%|███▏      | 8/25 [22:17<48:03, 169.63s/it] 36%|███▌      | 9/25 [25:19<46:15, 173.44s/it] 40%|████      | 10/25 [28:00<42:25, 169.68s/it] 44%|████▍     | 11/25 [30:35<38:35, 165.37s/it] 48%|████▊     | 12/25 [33:35<36:47, 169.83s/it] 52%|█████▏    | 13/25 [36:39<34:46, 173.89s/it] 56%|█████▌    | 14/25 [39:09<30:34, 166.80s/it] 60%|██████    | 15/25 [41:59<27:56, 167.67s/it] 64%|██████▍   | 16/25 [45:38<27:28, 183.13s/it] 68%|██████▊   | 17/25 [48:32<24:03, 180.50s/it] 72%|███████▏  | 18/25 [51:39<21:16, 182.41s/it] 76%|███████▌  | 19/25 [55:05<18:56, 189.40s/it] 80%|████████  | 20/25 [58:34<16:17, 195.48s/it] 84%|████████▍ | 21/25 [1:02:12<13:27, 201.98s/it] 88%|████████▊ | 22/25 [1:05:21<09:54, 198.22s/it] 92%|█████████▏| 23/25 [1:08:38<06:35, 197.68s/it] 96%|█████████▌| 24/25 [1:11:40<03:13, 193.07s/it]100%|██████████| 25/25 [1:16:02<00:00, 213.80s/it]100%|██████████| 25/25 [1:16:02<00:00, 182.50s/it]
  0%|          | 0/25 [00:00<?, ?it/s]  4%|▍         | 1/25 [04:04<1:37:44, 244.35s/it]  8%|▊         | 2/25 [1:16:49<9:27:30, 1480.44s/it] 12%|█▏        | 3/25 [2:29:59<14:22:55, 2353.45s/it] 16%|█▌        | 4/25 [2:36:02<10:14:40, 1756.21s/it] 20%|██        | 5/25 [2:40:53<7:18:56, 1316.81s/it]  24%|██▍       | 6/25 [2:45:40<5:19:09, 1007.86s/it] 28%|██▊       | 7/25 [4:14:25<11:30:55, 2303.08s/it] 32%|███▏      | 8/25 [5:27:39<13:50:13, 2930.23s/it]  0%|          | 0/25 [00:00<?, ?it/s]Adding 145 sources from /Users/caganze/research/splat//resources/Spectra/Public/LRIS-RED/ to spectral database
Adding 2404 sources from /Users/caganze/research/splat//resources/Spectra/Public/SPEX-PRISM/ to spectral database
Adding 89 sources from /Users/caganze/research/splat//resources/Spectra/Public/MAGE/ to spectral database
['aegis-01', 'aegis-02', 'aegis-03', 'aegis-04', 'aegis-05', 'aegis-06', 'aegis-07', 'aegis-08', 'aegis-09', 'aegis-10', 'aegis-12', 'aegis-13', 'aegis-14', 'aegis-15', 'aegis-18', 'aegis-19', 'aegis-21', 'aegis-23', 'aegis-24', 'aegis-25', 'aegis-26', 'aegis-27', 'aegis-28', 'aegis-11', 'cosmos-01', 'cosmos-03', 'cosmos-04', 'cosmos-05', 'cosmos-06', 'cosmos-07', 'cosmos-08', 'cosmos-09', 'cosmos-10', 'cosmos-11', 'cosmos-12', 'cosmos-13', 'cosmos-14', 'cosmos-15', 'cosmos-16', 'cosmos-17', 'cosmos-18', 'cosmos-19', 'cosmos-20', 'cosmos-21', 'cosmos-22', 'cosmos-23', 'cosmos-24', 'cosmos-25', 'cosmos-26', 'cosmos-27', 'cosmos-28', 'cosmos-02', 'uds-01', 'uds-02', 'uds-03', 'uds-04', 'uds-05', 'uds-06', 'uds-07', 'uds-08', 'uds-09', 'uds-10', 'uds-11', 'uds-12', 'uds-13', 'uds-14', 'uds-15', 'uds-17', 'uds-18', 'uds-20', 'uds-21', 'uds-22', 'uds-23', 'uds-24', 'uds-25', 'uds-26', 'uds-27', 'uds-28', 'uds-16', 'uds-19', 'goodsn-11', 'goodsn-111', 'goodsn-114', 'goodsn-12', 'goodsn-13', 'goodsn-14', 'goodsn-15', 'goodsn-16', 'goodsn-18', 'goodsn-23', 'goodsn-24', 'goodsn-25', 'goodsn-26', 'goodsn-27', 'goodsn-28', 'goodsn-31', 'goodsn-32', 'goodsn-34', 'goodsn-35', 'goodsn-36', 'goodsn-41', 'goodsn-42', 'goodsn-43', 'goodsn-44', 'goodsn-45', 'goodsn-46', 'goodss-01', 'goodss-02', 'goodss-03', 'goodss-04', 'goodss-05', 'goodss-06', 'goodss-08', 'goodss-09', 'goodss-10', 'goodss-11', 'goodss-12', 'goodss-13', 'goodss-14', 'goodss-15', 'goodss-16', 'goodss-17', 'goodss-18', 'goodss-19', 'goodss-20', 'goodss-21', 'goodss-22', 'goodss-24', 'goodss-25', 'goodss-26', 'goodss-27', 'goodss-28', 'goodss-29', 'goodss-30', 'goodss-31', 'goodss-32', 'goodss-33', 'goodss-34', 'goodss-35', 'goodss-36', 'goodss-37', 'goodss-38', 'goodsn-17', 'goodsn-21', 'goodsn-22', 'goodsn-33', 'goodss-07', 'goodsn-123', 'par334', 'par1', 'par10', 'par101', 'par103', 'par104', 'par105', 'par106', 'par107', 'par108', 'par11', 'par110', 'par111', 'par114', 'par115', 'par116', 'par119', 'par12', 'par120', 'par121', 'par122', 'par123', 'par124', 'par125', 'par126', 'par127', 'par128', 'par129', 'par13', 'par130', 'par132', 'par133', 'par134', 'par135', 'par136', 'par137', 'par138', 'par139', 'par14', 'par140', 'par141', 'par143', 'par144', 'par145', 'par146', 'par147', 'par148', 'par149', 'par15', 'par150', 'par151', 'par152', 'par153', 'par154', 'par155', 'par156', 'par157', 'par158', 'par159', 'par16', 'par160', 'par161', 'par162', 'par163', 'par165', 'par166', 'par167', 'par168', 'par169', 'par17', 'par170', 'par171', 'par172', 'par173', 'par174', 'par175', 'par176', 'par177', 'par179', 'par18', 'par181', 'par182', 'par183', 'par186', 'par188', 'par189', 'par19', 'par190', 'par191', 'par192', 'par193', 'par194', 'par195', 'par196', 'par197', 'par198', 'par199', 'par2', 'par20', 'par200', 'par201', 'par202', 'par203', 'par204', 'par205', 'par206', 'par209', 'par21', 'par210', 'par211', 'par212', 'par214', 'par215', 'par216', 'par217', 'par218', 'par219', 'par22', 'par220', 'par221', 'par222', 'par224', 'par226', 'par227', 'par228', 'par229', 'par23', 'par231', 'par232', 'par233', 'par234', 'par235', 'par236', 'par237', 'par238', 'par239', 'par24', 'par240', 'par241', 'par242', 'par243', 'par244', 'par245', 'par246', 'par247', 'par248', 'par249', 'par25', 'par250', 'par251', 'par252', 'par256', 'par257', 'par258', 'par259', 'par26', 'par260', 'par261', 'par262', 'par263', 'par264', 'par267', 'par268', 'par269', 'par27', 'par270', 'par271', 'par272', 'par273', 'par275', 'par277', 'par279', 'par28', 'par281', 'par288', 'par289', 'par29', 'par290', 'par292', 'par293', 'par294', 'par295', 'par297', 'par299', 'par30', 'par300', 'par301', 'par302', 'par303', 'par304', 'par307', 'par308', 'par309', 'par31', 'par311', 'par312', 'par313', 'par314', 'par315', 'par317', 'par319', 'par32', 'par320', 'par321', 'par322', 'par324', 'par325', 'par326', 'par328', 'par330', 'par332', 'par333', 'par335', 'par336', 'par337', 'par338', 'par34', 'par340', 'par341', 'par342', 'par343', 'par345', 'par346', 'par347', 'par348', 'par349', 'par35', 'par350', 'par352', 'par353', 'par354', 'par355', 'par356', 'par357', 'par358', 'par359', 'par36', 'par360', 'par361', 'par362', 'par364', 'par365', 'par367', 'par368', 'par369', 'par37', 'par370', 'par371', 'par372', 'par374', 'par375', 'par377', 'par378', 'par38', 'par380', 'par381', 'par382', 'par385', 'par386', 'par387', 'par388', 'par389', 'par39', 'par391', 'par394', 'par395', 'par396', 'par397', 'par398', 'par40', 'par400', 'par403', 'par404', 'par405', 'par406', 'par408', 'par409', 'par41', 'par411', 'par412', 'par413', 'par416', 'par417', 'par420', 'par422', 'par425', 'par427', 'par428', 'par43', 'par430', 'par431', 'par432', 'par433', 'par434', 'par435', 'par436', 'par437', 'par438', 'par439', 'par44', 'par440', 'par441', 'par442', 'par443', 'par444', 'par445', 'par446', 'par449', 'par45', 'par450', 'par451', 'par452', 'par453', 'par454', 'par456', 'par457', 'par458', 'par46', 'par461', 'par462', 'par463', 'par464', 'par465', 'par466', 'par467', 'par468', 'par469', 'par47', 'par471', 'par472', 'par473', 'par474', 'par476', 'par477', 'par478', 'par480', 'par481', 'par482', 'par483', 'par49', 'par5', 'par50', 'par51', 'par52', 'par53', 'par54', 'par55', 'par56', 'par57', 'par58', 'par59', 'par6', 'par64', 'par65', 'par66', 'par68', 'par69', 'par71', 'par72', 'par73', 'par74', 'par75', 'par76', 'par77', 'par79', 'par80', 'par81', 'par82', 'par83', 'par84', 'par85', 'par86', 'par87', 'par88', 'par89', 'par90', 'par91', 'par92', 'par93', 'par94', 'par95', 'par96', 'par97', 'par98', 'par99']
  4%|▍         | 1/25 [01:46<42:42, 106.78s/it]  8%|▊         | 2/25 [03:34<41:05, 107.20s/it] 12%|█▏        | 3/25 [05:25<39:41, 108.27s/it] 16%|█▌        | 4/25 [07:13<37:52, 108.20s/it] 20%|██        | 5/25 [09:02<36:07, 108.39s/it] 24%|██▍       | 6/25 [10:54<34:38, 109.38s/it] 28%|██▊       | 7/25 [12:44<32:53, 109.65s/it] 32%|███▏      | 8/25 [14:37<31:20, 110.62s/it] 36%|███▌      | 9/25 [16:30<29:43, 111.49s/it] 40%|████      | 10/25 [18:23<27:55, 111.69s/it] 44%|████▍     | 11/25 [20:14<26:04, 111.73s/it] 48%|████▊     | 12/25 [22:05<24:09, 111.53s/it] 52%|█████▏    | 13/25 [23:59<22:24, 112.04s/it] 56%|█████▌    | 14/25 [25:52<20:36, 112.42s/it] 60%|██████    | 15/25 [27:42<18:36, 111.61s/it] 64%|██████▍   | 16/25 [29:36<16:52, 112.51s/it] 68%|██████▊   | 17/25 [31:31<15:06, 113.26s/it] 72%|███████▏  | 18/25 [33:29<13:21, 114.53s/it] 76%|███████▌  | 19/25 [35:29<11:38, 116.34s/it] 80%|████████  | 20/25 [37:22<09:36, 115.31s/it] 84%|████████▍ | 21/25 [39:15<07:38, 114.55s/it] 88%|████████▊ | 22/25 [41:17<05:50, 116.78s/it] 92%|█████████▏| 23/25 [43:22<03:58, 119.12s/it] 96%|█████████▌| 24/25 [2:14:31<28:43, 1723.94s/it]  0%|          | 0/25 [00:00<?, ?it/s]Adding 145 sources from /Users/caganze/research/splat//resources/Spectra/Public/LRIS-RED/ to spectral database
Adding 2404 sources from /Users/caganze/research/splat//resources/Spectra/Public/SPEX-PRISM/ to spectral database
Adding 89 sources from /Users/caganze/research/splat//resources/Spectra/Public/MAGE/ to spectral database
  4%|▍         | 1/25 [09:11<3:40:46, 551.94s/it]  8%|▊         | 2/25 [18:32<3:32:35, 554.57s/it] 12%|█▏        | 3/25 [27:48<3:23:25, 554.82s/it] 16%|█▌        | 4/25 [37:00<3:13:54, 554.02s/it] 20%|██        | 5/25 [46:15<3:04:50, 554.55s/it] 24%|██▍       | 6/25 [55:31<2:55:44, 554.97s/it]